project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true
files:
  - source: resources/src/commonMain/moko-resources/base/strings.xml
    translation: resources/src/commonMain/moko-resources/%locale%/strings.xml
    ignore:
      - resources/src/commonMain/moko-resources/images/
      - resources/src/commonMain/moko-resources/files/
  - source: resources/src/commonMain/moko-resources/base/plurals.xml
    translation: resources/src/commonMain/moko-resources/%locale%/plurals.xml
    ignore:
      - resources/src/commonMain/moko-resources/images/
      - resources/src/commonMain/moko-resources/files/
