package com.hyperion.model

data class Channel(
    val allowedRegions: List<String>,
    val author: String,
    val authorBanners: List<AuthorBanner>,
    val authorId: String,
    val authorThumbnails: List<AuthorThumbnail>,
    val authorUrl: String,
    val autoGenerated: Boolean,
    val description: String,
    val descriptionHtml: String,
    val isFamilyFriendly: Boolean,
    val joined: Long,
    val latestVideos: List<LatestVideo>,
    val paid: Boolean,
    val relatedChannels: List<RelatedChannel>,
    val subCount: Int,
    val totalViews: Long
) {
    data class AuthorBanner(
        val width: Int,
        val height: Int,
        val url: String
    )

    data class LatestVideo(
        val author: String,
        val authorId: String,
        val authorUrl: String,
        val description: String,
        val descriptionHtml: String,
        val lengthSeconds: Int,
        val paid: Boolean,
        val premium: Boolean,
        val published: Long,
        val publishedText: String,
        val title: String,
        val videoId: String,
        val videoThumbnails: List<VideoThumbnail>,
        val viewCount: Long
    )

    data class RelatedChannel(
        val author: String,
        val authorId: String,
        val authorThumbnails: List<AuthorThumbnail>,
        val authorUrl: String
    )
}