name: "Setup environment"
description: ""

inputs:
  architecture:
    description: 'Architecture of the JDK (e.g., x64, x86)'
    required: false
    default: 'x64'

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        architecture: ${{ inputs.architecture }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4