name: Build Debug APK

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
    group: "build-debug-apk"
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Build project with Gradle
        run: chmod +x ./gradlew && ./gradlew app:assembleDebug --no-daemon

      - uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: |
            app/build/outputs/apk/debug/app-debug.apk
      
      - name: Automatic Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "debug"
          prerelease: true
          title: "Automatic Debug Build"
          files: |
              app/build/outputs/apk/debug/app-debug.apk
